sudo: false
language: java
jdk:
  - openjdk8
before_install:
  - cd OpenDataPushService
  - echo 'MAVEN_OPTS="-Xms512m -Xmx1024m -XX:PermSize=256m -XX:MaxPermSize=512m"' >~/.mavenrc
# default install is mvn install --quiet -DskipTests=true
install: travis_wait 30 mvn --show-version --quiet -T 1C clean install
script:
  # invoker.streamLogs: we cannot access to log files through Travis web ui, so display everything in the console
  - mvn --show-version verify -Dinvoker.streamLogs=true
after_failure:
  - cat target/logs/*
notifications:
  email:
    - connectpa@tirasa.net
